// <auto-generated />
namespace PurchaseManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class edit23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit23));
        
        string IMigrationMetadata.Id
        {
            get { return "201807060659373_edit23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
